qcar:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  rr_controller:
    type: velocity_controllers/JointVelocityController
    joint: base_wheelrr_joint
    pid: {p: 1, i: 0, d: 0}

  rl_controller:
    type: velocity_controllers/JointVelocityController
    joint: base_wheelrl_joint
    pid: {p: 1, i: 0, d: 0}

  base_fr_controller:
    type: position_controllers/JointPositionController
    joint: base_hubfr_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  base_fl_controller:
    type: position_controllers/JointPositionController
    joint: base_hubfl_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}